name: Problem issue for project tequila
description: Create a problem issue for the project tequila
projects: 
  - unam-transients/8
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      placeholder: Describe your problem here ...
